# Site settings
title: My GitHub Pages Site
email: your-email@example.com
description: >- # this means to ignore newlines until ">"
  Welcome to my GitHub Pages site. This is an introductory page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
